[package]
name = "frontend"
version = "0.1.0"
edition = "2024"

[features]
default = []
compiled-game = ["dep:game"]

[dependencies]
emu-core = { path = "../emu-core" }
bytemuck = { version = "1.23", features = [ "derive" ] }
game = { path = "../game", optional = true }
lru-cache = { path = "../lru-cache" }

[target.'cfg(not(target_os = "horizon"))'.dependencies]
# sdl2 = { version = "0.38", features = [ "use-pkgconfig" ] }
sdl2 = { git = "https://github.com/SKyletoft/rust-sdl2", features = [ "use-pkgconfig" ] } # Mirroring fix from master, use release when 0.39 or 0.38.1

[target.'cfg(target_os = "horizon")'.dependencies]
ctru-rs = { git = "https://github.com/rust3ds/ctru-rs" }
citro2d = { path = "../citro3d-rs/citro2d" }

[package.metadata.cargo-3ds]
romfs_dir = "romfs"
