[package]
name = "frontend"
version = "0.1.0"
edition = "2024"

[features]
compiled-game = ["dep:game"]

[dependencies]
bytemuck = { version = "1.23", features = [ "derive" ] }
game = { path = "../game", optional = true }
lru-cache = { path = "../lru-cache" }

# Desktop
[target.'cfg(target_os = "linux")'.dependencies]
# sdl2 = { version = "0.38", features = [ "use-pkgconfig" ] }
sdl2 = { git = "https://github.com/SKyletoft/rust-sdl2", features = [ "use-pkgconfig" ] } # Mirroring fix from master, use release when 0.39 or 0.38.1
emu-core = { path = "../emu-core", features = [ "std" ] }

# 3DS
[target.'cfg(target_os = "horizon")'.dependencies]
ctru-rs = { git = "https://github.com/rust3ds/ctru-rs" }
citro2d = { path = "../citro3d-rs/citro2d" }
emu-core = { path = "../emu-core", features = [ "std" ] }

# Badge
[target.'cfg(target_os = "none")'.dependencies]
emu-core = { path = "../emu-core" }
esp-hal = { version = "1.2", features = ["esp32s3", "unstable"] }
esp-bootloader-esp-idf = { version = "0.6", features = ["esp32s3"] }
esp-println = { version = "0.18", features = ["esp32s3"] }
embedded-hal-bus = "0.3"
embedded-hal = "1"
embedded-graphics = "0.8"
mipidsi = "0.10"
static_cell = "2.1"

[package.metadata.cargo-3ds]
romfs_dir = "romfs"
