[workspace]
resolver = "3"
members = [ "emu-core", "frontend", "nesc", "game", "benchmark", "breakout" ]

[profile.dev]
overflow-checks = false

[profile.dev.package.emu-core]
opt-level = 1

[profile.dev.package.frontend]
opt-level = 1

[profile.dev.package.nesc]
opt-level = 0

[profile.dev.package.game]
opt-level = 0

[profile.dev.package.benchmark]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"
overflow-checks = false
# panic = "abort"
