[workspace]
resolver = "3"
members = [ "emu-core", "linux", "console", "nesc", "game", "benchmark", "breakout" ]

[profile.dev]
opt-level = 1
overflow-checks = false

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"
overflow-checks = false
# panic = "abort"
