#include "interface.h"

// C-implementations of NES instructions

void lax_zero_page(State *state, uint8_t val) {}
void lax_zero_page_y(State *state, uint8_t val) {}
void lax_absolute(State *state, uint8_t val) {}
void lax_absolute_y(State *state, uint8_t val) {}
void lax_indirect_x(State *state, uint8_t val) {}
void lax_indirect_y(State *state, uint8_t val) {}
void sax_zero_page(State *state, uint8_t val) {}
void sax_zero_page_y(State *state, uint8_t val) {}
void sax_absolute(State *state, uint8_t val) {}
void sax_indirect_x(State *state, uint8_t val) {}
void dcp_zero_page(State *state, uint8_t val) {}
void dcp_zero_page_x(State *state, uint8_t val) {}
void dcp_absolute(State *state, uint8_t val) {}
void dcp_absolute_x(State *state, uint8_t val) {}
void dcp_absolute_y(State *state, uint8_t val) {}
void dcp_indirect_x(State *state, uint8_t val) {}
void dcp_indirect_y(State *state, uint8_t val) {}
void isc_zero_page(State *state, uint8_t val) {}
void isc_zero_page_x(State *state, uint8_t val) {}
void isc_absolute(State *state, uint8_t val) {}
void isc_absolute_x(State *state, uint8_t val) {}
void isc_absolute_y(State *state, uint8_t val) {}
void isc_indirect_x(State *state, uint8_t val) {}
void isc_indirect_y(State *state, uint8_t val) {}
void rla_zero_page(State *state, uint8_t val) {}
void rla_zero_page_x(State *state, uint8_t val) {}
void rla_absolute(State *state, uint8_t val) {}
void rla_absolute_x(State *state, uint8_t val) {}
void rla_absolute_y(State *state, uint8_t val) {}
void rla_indirect_x(State *state, uint8_t val) {}
void rla_indirect_y(State *state, uint8_t val) {}
void rra_zero_page(State *state, uint8_t val) {}
void rra_zero_page_x(State *state, uint8_t val) {}
void rra_absolute(State *state, uint8_t val) {}
void rra_absolute_x(State *state, uint8_t val) {}
void rra_absolute_y(State *state, uint8_t val) {}
void rra_indirect_x(State *state, uint8_t val) {}
void rra_indirect_y(State *state, uint8_t val) {}
void slo_zero_page(State *state, uint8_t val) {}
void slo_zero_page_x(State *state, uint8_t val) {}
void slo_absolute(State *state, uint8_t val) {}
void slo_absolute_x(State *state, uint8_t val) {}
void slo_absolute_y(State *state, uint8_t val) {}
void slo_indirect_x(State *state, uint8_t val) {}
void slo_indirect_y(State *state, uint8_t val) {}
void sre_zero_page(State *state, uint8_t val) {}
void sre_zero_page_x(State *state, uint8_t val) {}
void sre_absolute(State *state, uint8_t val) {}
void sre_absolute_x(State *state, uint8_t val) {}
void sre_absolute_y(State *state, uint8_t val) {}
void sre_indirect_x(State *state, uint8_t val) {}
void sre_indirect_y(State *state, uint8_t val) {}
void anc(State *state, uint8_t val) {}
void alr(State *state, uint8_t val) {}
void arr(State *state, uint8_t val) {}
void axs(State *state, uint8_t val) {}
void las(State *state, uint8_t val) {}
void tas(State *state, uint8_t val) {}
void shy(State *state, uint8_t val) {}
void shx(State *state, uint8_t val) {}
void ahx_absolute_y(State *state, uint8_t val) {}
void ahx_indirect_y(State *state, uint8_t val) {}
